package fis.ftu.model;
// Generated Jul 13, 2019 1:15:12 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer", catalog = "survey")
public class Answer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idanswer;
	//private AnswerSheet answerSheet;
	private Question question;
	private String answer;

	public Answer() {
	}

	public Answer(int idanswer, AnswerSheet answerSheet, Question question) {
		this.idanswer = idanswer;
		//this.answerSheet = answerSheet;
		this.question = question;
	}

	public Answer(int idanswer, AnswerSheet answerSheet, Question question, String answer) {
		this.idanswer = idanswer;
		//this.answerSheet = answerSheet;
		this.question = question;
		this.answer = answer;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idanswer", unique = true, nullable = false)
	public int getIdanswer() {
		return this.idanswer;
	}

	public void setIdanswer(int idanswer) {
		this.idanswer = idanswer;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idanswer_sheet", nullable = false)
	public AnswerSheet getAnswerSheet() {
		return this.answerSheet;
	}

	public void setAnswerSheet(AnswerSheet answerSheet) {
		this.answerSheet = answerSheet;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "answer")
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
