package fis.ftu.model;
// Generated Jul 13, 2019 1:15:12 AM by Hibernate Tools 5.2.10.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * AnswerSheet generated by hbm2java
 */
@Entity
@Table(name = "answer_sheet", catalog = "survey")
public class AnswerSheet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idanswerSheet;
	private Participant participant;
	private Survey survey;
	private Date datecreate;
	private List<Answer> answers = new ArrayList<Answer>(0);

	public AnswerSheet() {
	}

	public AnswerSheet(int idanswerSheet, Participant participant, Survey survey) {
		this.idanswerSheet = idanswerSheet;
		this.participant = participant;
		this.survey = survey;
	}

	public AnswerSheet(int idanswerSheet, Participant participant, Survey survey, Date datecreate,
			List<Answer> answers) {
		this.idanswerSheet = idanswerSheet;
		this.participant = participant;
		this.survey = survey;
		this.datecreate = datecreate;
		this.answers = answers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idanswer_sheet", unique = true, nullable = false)
	public int getIdanswerSheet() {
		return this.idanswerSheet;
	}

	public void setIdanswerSheet(int idanswerSheet) {
		this.idanswerSheet = idanswerSheet;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "idparticipant")
	public Participant getParticipant() {
		return this.participant;
	}

	public void setParticipant(Participant participant) {
		this.participant = participant;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "idsurvey", nullable = false)
	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datecreate", length = 19)
	public Date getDatecreate() {
		return this.datecreate;
	}

	public void setDatecreate(Date datecreate) {
		this.datecreate = datecreate;
	}

	@OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "idanswer_sheet")
	public List<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(List<Answer> answers) {
		this.answers = answers;
	}

}
