package fis.ftu.model;
// Generated Jul 13, 2019 1:15:12 AM by Hibernate Tools 5.2.10.Final

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Choice generated by hbm2java
 */
@Entity
@Table(name = "choice", catalog = "survey")
public class Choice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idchoice;	
	private String answer;
	private String type;

	public Choice() {
	}

	public Choice(int idchoice, Question question) {
		this.idchoice = idchoice;		
	}

	public Choice(int idchoice, Question question, String answer, String type) {
		this.idchoice = idchoice;		
		this.answer = answer;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idchoice", unique = true, nullable = false)
	public int getIdchoice() {
		return this.idchoice;
	}

	public void setIdchoice(int idchoice) {
		this.idchoice = idchoice;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idquestion", nullable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}*/

	@Column(name = "answer", length = 200)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (!(o instanceof Choice))
			return false;
		Choice choice = (Choice) o;
		return Objects.equals(idchoice, choice.idchoice);
	}

	@Override
	public int hashCode() {
		return Objects.hash(idchoice);
	}

}
