package fis.ftu.model;
// Generated Jul 13, 2019 1:15:12 AM by Hibernate Tools 5.2.10.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Participant generated by hbm2java
 */
@Entity
@Table(name = "participant", catalog = "survey")
public class Participant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idparticipant;
	private String name;
	private String email;
	private String phone;
	//private List<AnswerSheet> answerSheets = new ArrayList<AnswerSheet>(0);

	public Participant() {
	}

	public Participant(int idparticipant) {
		this.idparticipant = idparticipant;
	}

	public Participant(int idparticipant, String name, String email, String phone, List<AnswerSheet> answerSheets) {
		this.idparticipant = idparticipant;
		this.name = name;
		this.email = email;
		this.phone = phone;
		//this.answerSheets = answerSheets;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idparticipant", unique = true, nullable = false)
	public int getIdparticipant() {
		return this.idparticipant;
	}

	public void setIdparticipant(int idparticipant) {
		this.idparticipant = idparticipant;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "participant")
	public List<AnswerSheet> getAnswerSheets() {
		return this.answerSheets;
	}

	public void setAnswerSheets(List<AnswerSheet> answerSheets) {
		this.answerSheets = answerSheets;
	}*/

}
