package fis.ftu.model;
// Generated Jul 13, 2019 1:15:12 AM by Hibernate Tools 5.2.10.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "survey")
public class Permission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpermission;
	private String listpermission;

	public Permission() {
	}

	public Permission(int idpermission) {
		this.idpermission = idpermission;
	}

	public Permission(int idpermission, String listpermission, List<User> users) {
		this.idpermission = idpermission;
		this.listpermission = listpermission;		
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idpermission", unique = true, nullable = false)
	public int getIdpermission() {
		return this.idpermission;
	}

	public void setIdpermission(int idpermission) {
		this.idpermission = idpermission;
	}

	@Column(name = "listpermission", length = 200)
	public String getListpermission() {
		return this.listpermission;
	}

	public void setListpermission(String listpermission) {
		this.listpermission = listpermission;
	}	
}
